volumes:
    postgres-data:
        external: true
    pg-admin:
        external: true
services:
    postgres:
        image: postgres:14.5-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: packit
            POSTGRES_USER: packit1
            POSTGRES_DB: packit
        ports:
            - 15432:5432
    fastapi:
        environment:
            DATABASE_URL: postgresql://packit1:packit@postgres/packit
            CORS_HOST: http://localhost:5173
            DATABASE_URL: postgresql://user:user@postgres/user
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
        ports:
            - "5173:5173"
    pg-admin:
        image: dpage/pgadmin4
        volumes:
            - pg-admin:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: packit@packit.com
            PGADMIN_DEFAULT_PASSWORD: packit
            PGADMIN_DISABLE_POSTFIX: 1
